


import { LeaderboardUser, MarketplaceItem, Transaction, AssetType, AssetLanguage, UserAsset, UserActivity, Post, AppAttachment, MarketplaceItemType, TradableAsset, PriceDataPoint, StakingPool, InvestmentStrategy, RiskLevel, Organization, ChatMessage, ThemeItem } from './types';

const userPosts = [
    { name: 'ChainWavey931', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'FlexMaster694', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainKing198', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'MaxShark72', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaGod311', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxBoss464', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark879', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockGod429', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroWave786', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostBoss541', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ZeroShark207', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoWavey622', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIKing338', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIBoss52', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostRider90', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ZeroWavey675', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostWave174', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostKing397', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIShark190', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'MaxMaster465', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainWavey881', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonGod815', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlLegend378', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AILegend710', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxGod634', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonKing811', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'SigmaGod762', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainHunter20', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ChainGod500', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroWavey894', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ChainLord690', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark520', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'GhostWavey949', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'FlexHunter752', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonLord603', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ChainBoss873', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexMaster861', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonWave831', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing950', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIHunter642', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ZeroBoss581', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'BlockRider275', post: 'My dog just got more followers than me, wtf' },
    { name: 'BlockHunter814', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxHunter986', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexLord774', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroHunter930', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonRider571', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxMaster30', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'BlockLegend4', post: 'My dog just got more followers than me, wtf' },
    { name: 'SigmaLord966', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'MaxLegend148', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ZeroWavey135', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'HodlShark321', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaKing481', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlMaster390', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLegend576', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'NeonShark135', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'HodlLord23', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'GhostLord832', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxKing814', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexShark422', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'GhostGod143', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'MaxHunter316', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'HodlLord610', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'GhostRider755', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonLegend430', post: 'My dog just got more followers than me, wtf' },
    { name: 'NeonLord523', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainKing232', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'MaxWavey149', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxBoss545', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxRider689', post: 'Story of my life: broke, horny, and confused' },
    { name: 'MaxShark926', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'CryptoWave575', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxLord114', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroGod479', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexGod408', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroShark254', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroGod47', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing55', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainRider711', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'CryptoWavey305', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIKing347', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'FlexWavey478', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIWavey71', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonLord241', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroRider214', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ChainLegend612', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ChainMaster66', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaLegend541', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIWave903', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockLegend444', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIMaster955', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIRider3', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'FlexGod611', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaWave261', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlBoss662', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxKing319', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexWave143', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaLegend323', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlHunter469', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainKing207', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostRider910', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockKing795', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroLord789', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxWavey508', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonBoss275', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainMaster173', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlRider941', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockKing697', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'FlexShark700', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'HodlHunter871', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonWave528', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainWavey646', post: 'My dog just got more followers than me, wtf' },
    { name: 'SigmaLord762', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexLord689', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexLord121', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'MaxShark377', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'BlockGod909', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ChainWave368', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroLord295', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonWave687', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIBoss948', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'ChainHunter303', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'AILegend991', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AIWave14', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIRider410', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark420', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ZeroWave223', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ChainKing973', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'AILegend71', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoKing775', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark511', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaMaster694', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlKing747', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLord714', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIWave904', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaGod872', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'BlockKing589', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaHunter355', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonMaster54', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'BlockWave220', post: 'Story of my life: broke, horny, and confused' },
    { name: 'SigmaHunter57', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxRider527', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxLord539', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaShark849', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIHunter430', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlHunter791', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexLegend874', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockWavey606', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxGod142', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonHunter394', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'NeonGod417', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexKing49', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIWavey564', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaMaster744', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'CryptoWave600', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIHunter564', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'FlexHunter677', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxRider651', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroLegend462', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxGod174', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroLegend702', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexShark27', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'NeonGod379', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostMaster996', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'AIHunter556', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'CryptoHunter62', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'FlexHunter932', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'MaxShark605', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'FlexLegend672', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'GhostLord125', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexGod326', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexWave281', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroLord749', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoHunter243', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlShark713', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxWave804', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaHunter478', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'FlexRider542', post: 'My dog just got more followers than me, wtf' },
    { name: 'CryptoGod848', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexHunter309', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaWave377', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'NeonMaster160', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AIBoss855', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'BlockWavey751', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexKing929', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIRider88', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'SigmaRider157', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ChainGod158', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWavey474', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ChainMaster783', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'GhostBoss906', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonRider820', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonWave946', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonHunter580', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'SigmaKing184', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ChainKing212', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaLegend355', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing26', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'HodlLegend63', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'HodlHunter725', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockBoss241', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonKing710', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'BlockLegend205', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'NeonLegend162', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLegend931', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AIShark426', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLegend948', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostWave727', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxWave943', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostRider503', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockBoss147', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ZeroGod227', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroWave57', post: 'My dog just got more followers than me, wtf' },
    { name: 'ChainLord543', post: 'Story of my life: broke, horny, and confused' },
    { name: 'CryptoWavey6', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'CryptoLegend337', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'CryptoBoss384', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIKing593', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxHunter244', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxGod287', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaMaster745', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'AIHunter193', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaWavey814', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ZeroLegend234', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIWavey384', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoShark629', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxLegend128', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonLord43', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaHunter174', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexBoss186', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexHunter241', post: 'Story of my life: broke, horny, and confused' },
    { name: 'MaxRider555', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'SigmaWavey760', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'NeonShark159', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'ChainWave102', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'MaxGod836', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexGod592', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWave214', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlMaster266', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroKing295', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainLegend902', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'GhostWave995', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockLord500', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonRider507', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostKing958', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroWavey25', post: 'My dog just got more followers than me, wtf' },
    { name: 'AIShark214', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLegend404', post: 'Story of my life: broke, horny, and confused' },
    { name: 'SigmaRider608', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexWavey216', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWave348', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxHunter443', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIShark321', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoWave787', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing842', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing912', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainLord361', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'HodlRider304', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'CryptoShark390', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainMaster661', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxHunter382', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLord340', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'CryptoGod625', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonWavey859', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroHunter511', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostWave258', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostKing121', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonWavey293', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonHunter564', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxWave299', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockRider924', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaKing596', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaLegend868', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockRider357', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaBoss443', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing16', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockBoss240', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaLord768', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster949', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainLegend46', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaLegend313', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoRider955', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexWave574', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoMaster315', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaRider782', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ZeroWave346', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster752', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexBoss834', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'AIMaster324', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'CryptoWave478', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AILord770', post: 'Story of my life: broke, horny, and confused' },
    { name: 'GhostShark111', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'CryptoShark698', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'FlexHunter351', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIWave473', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroKing183', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'MaxKing804', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'HodlWavey590', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostKing135', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'MaxMaster915', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockLord781', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'BlockKing441', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoKing519', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWave217', post: 'My dog just got more followers than me, wtf' },
    { name: 'BlockLegend323', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonRider889', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ChainShark989', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'BlockBoss34', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainLegend1', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaShark396', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ZeroMaster898', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroWave455', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'HodlWave630', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'GhostShark253', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainBoss961', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AIKing288', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'SigmaHunter711', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxHunter420', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonWavey958', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxLegend979', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlWave282', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonKing846', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'HodlWave50', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'GhostShark531', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlWave27', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostBoss208', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxBoss441', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'CryptoHunter722', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlWavey482', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'BlockWave30', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainLord801', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlWave722', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlLegend331', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'GhostRider396', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'MaxHunter434', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonMaster726', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ZeroWave456', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostMaster828', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AILord100', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWave956', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroShark488', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'FlexWave943', post: 'My dog just got more followers than me, wtf' },
    { name: 'CryptoGod471', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaHunter361', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexWave700', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIWave753', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'CryptoBoss978', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexGod492', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaHunter372', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ZeroShark196', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostMaster171', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainLegend514', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockRider111', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AILegend266', post: 'My dog just got more followers than me, wtf' },
    { name: 'GhostWavey225', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxHunter528', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaLord812', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster46', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroMaster98', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'HodlLord510', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIHunter153', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ChainLord758', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostLord530', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroLord700', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonHunter652', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIHunter702', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlWave220', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'BlockWave518', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlWave651', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'CryptoHunter817', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'SigmaHunter148', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaKing472', post: 'My dog just got more followers than me, wtf' },
    { name: 'ZeroWavey808', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'FlexBoss61', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ChainWavey23', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ChainHunter338', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'NeonWave132', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainHunter606', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'MaxRider66', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaHunter356', post: 'Story of my life: broke, horny, and confused' },
    { name: 'BlockShark193', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ZeroWavey188', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'CryptoKing208', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexLegend970', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlShark433', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWavey901', post: 'Story of my life: broke, horny, and confused' },
    { name: 'GhostKing320', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlMaster92', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainGod373', post: 'Hodl? Nah, I sold for tacos' },
];

const memeImages = [
    'https://placehold.co/600x400/000000/FFFFFF/png?text=Me+pretending+to+understand+the+PR+comments',
    'https://placehold.co/600x600/000000/FFFFFF/png?text=It\'s+not+a+bug,+it\'s+a+feature',
    'https://placehold.co/600x500/000000/FFFFFF/png?text=CSS',
    'https://placehold.co/500x600/000000/FFFFFF/png?text=Client:\'Can+you+just...\'',
    'https://placehold.co/600x450/000000/FFFFFF/png?text=Works+on+my+machine',
];
const mockApps: AppAttachment[] = [
    { name: 'Spaghetti-fy', description: 'Turns your clean, readable code into a delicious bowl of spaghetti. Impress your colleagues!', language: 'JavaScript', code: 'alert("Mama mia!")' },
    { name: 'Div-orce Kramer', description: 'A library that exclusively and aggressively centers divs. Nothing else.', language: 'Python', code: 'print("Centered.")' },
    { name: 'Clippy-as-a-Service', description: 'An API that just returns annoying, unhelpful suggestions. Now with more condescension!', language: 'Rust', code: 'fn main() { /* Are you sure you want to do that? */ }' },
    { name: 'Git Blame-r', description: 'A tool that automatically finds who to blame for the bug you just found.', language: 'Go', code: 'package main' },
];

export const MOCK_POSTS: Post[] = Array.from({ length: 1000 }, (_, i) => {
    const postData = userPosts[i % userPosts.length];
    const authorName = postData.name;
    const content = postData.post;

    const hasImage = Math.random() > 0.85; // Images are more special
    const hasAttachment = !hasImage && Math.random() > 0.9;
    
    const app = mockApps[Math.floor(Math.random() * mockApps.length)];
    
    return {
        id: `post-${i}`,
        authorName,
        authorAvatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=${authorName.replace(/\s/g, '')}`,
        content,
        image: hasImage ? memeImages[Math.floor(Math.random() * memeImages.length)] : undefined,
        attachment: hasAttachment ? app : undefined,
        likes: Math.floor(Math.random() * 2048),
        comments: Math.floor(Math.random() * 512),
        timestamp: `${Math.floor(Math.random() * 23) + 1}h ago`,
    };
});


export const MOCK_MARKETPLACE_ITEMS: MarketplaceItem[] = [
    { id: '1', name: 'Slightly Used For-Loop', description: 'Only used on Sundays. A bit of wear and tear but gets the job done. Final sale.', author: 'Loop Peddler', price: 50n, type: 'Snippet', rating: 4.2, reviews: 120, tags: ['utility', 'loop'], version: '1.0.1', language: 'JavaScript', code: 'for (let i = 0; i < 100; i++) {\n  console.log("This loop has seen things... but still works! Iteration: " + i);\n}' },
    { id: '2', name: 'How to Exit Vim: The Course', description: 'An interactive, 12-week course on the ancient art of closing the Vim editor.', author: 'Escape Artist', price: 9999n, type: 'Course', rating: 4.9, reviews: 2048, tags: ['education', 'vim', 'essential'], version: '3.2.0' },
    { id: '3', name: 'Emotional Support Plugin', description: 'A plugin that replaces all error messages with compliments and cat pictures.', author: 'Kind Coder', price: 1500n, type: 'Plugin', rating: 5.0, reviews: 987, tags: ['mental health', 'fun', 'ide'], version: '2.0.0', isFeatured: true, language: 'JavaScript', code: 'console.error = function(message) {\n  console.log("✨ You are a brilliant developer! ✨ Don\'t worry about this: ", message);\n  // In a real plugin, you would display a cat picture here.\n};' },
    { id: '4', name: 'Over-engineered AI "Hello World"', description: 'A hyper-optimized, enterprise-grade "Hello World" template, powered by a proprietary neural network. Future-proof your greetings.', author: 'VectorBro', price: 25000n, type: 'Template', rating: 2.1, reviews: 42, tags: ['ai', 'enterprise', 'hype'], version: '0.1.0-alpha', language: 'Go', code: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// This is running on a proprietary, hyper-optimized neural network.\n\tfmt.Println("Hello, AI Overlord!")\n}' },
    { id: '5', name: 'Go Microservice Kit', description: 'Starter kit for building scalable microservices in Go.', author: 'GoPioneers', price: 1800n, type: 'Template', rating: 4.7, reviews: 312, tags: ['backend', 'go', 'microservice'], version: '1.5.3', language: 'Go', code: 'package main\n\nimport (\n\t"fmt"\n\t"net/http"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tfmt.Fprintf(w, "Hello from your Go microservice!")\n}\n\nfunc main() {\n\thttp.HandleFunc("/", handler)\n\thttp.ListenAndServe(":8080", nil)\n}' },
    { id: '6', name: 'Python Data Scraping Script', description: 'A snippet to easily scrape web data.', author: 'DataMiners', price: 750n, type: 'Snippet', rating: 4.5, reviews: 250, tags: ['data', 'python', 'scraping'], version: '2.1.0', language: 'Python', code: 'import requests\nfrom bs4 import BeautifulSoup\n\nURL = "http://example.com"\npage = requests.get(URL)\nsoup = BeautifulSoup(page.content, "html.parser")\n\n# Find all h1 tags\nresults = soup.find_all("h1")\nfor result in results:\n\tprint(result.text)' },
    { id: '7', name: 'MarketGPT Pro', description: 'An AI model that predicts stock market trends with questionable accuracy. High risk, high reward!', author: 'AI Prophet', price: 50000n, type: 'AI Model', rating: 4.8, reviews: 750, tags: ['finance', 'prediction', 'LLM'], version: '2.3.0', isFeatured: true, language: 'Python', code: 'import random\n\ndef predict_market(ticker):\n\t# Advanced AI algorithm (patent pending)\n\tprint(f"Analyzing {ticker}...")\n\tif random.random() > 0.5:\n\t\treturn "📈 Market is going UP! To the moon!"\n\telse:\n\t\treturn "📉 Market is going DOWN! Sell everything!"\n\nprint(predict_market("ATLAS"))' },
    { id: '8', name: 'Investor Pitch Deck Prompts', description: 'A bundle of finely-tuned prompts to generate a compelling investor pitch deck for your startup.', author: 'Prompt Engineer', price: 2500n, type: 'Prompt', rating: 4.9, reviews: 430, tags: ['business', 'startup', 'generation'], version: '1.2.0', language: 'JavaScript', code: 'const investorPitchPrompt = `Generate a 10-slide investor pitch deck for a new AI-powered code marketplace called "CodeAtlas". The slides should cover: \n1. Problem Statement \n2. Solution \n3. Market Size \n4. Product Demo \n5. Business Model \n6. Go-to-Market Strategy \n7. Team \n8. Financial Projections \n9. The Ask \n10. Contact Info`;' },
    { id: '9', name: 'Social Media Marketing Agent', description: 'A complete workflow that writes, schedules, and posts engaging content across your social media channels.', author: 'AutoSocial', price: 12000n, type: 'Workflow', rating: 4.6, reviews: 512, tags: ['automation', 'marketing', 'social media'], version: '3.0.1', isFeatured: true, language: 'Python', code: 'class SocialMediaAgent:\n\tdef __init__(self, topic):\n\t\tself.topic = topic\n\n\tdef generate_post(self):\n\t\treturn f"🚀 Big news in {self.topic}! #AI #{self.topic.replace(\' \',\'\')} #Future"\n\n\tdef schedule_post(self, post):\n\t\tprint(f\'Scheduling post: "{post}"\')\n\n\tdef run(self):\n\t\tpost = self.generate_post()\n\t\tself.schedule_post(post)\n\nagent = SocialMediaAgent("AI Development")\nagent.run()' },
    { id: '10', name: 'Code Review AI Bot', description: 'An AI model that automatically reviews pull requests, suggests improvements, and spots bugs.', author: 'DevHelper AI', price: 8000n, type: 'AI Model', rating: 4.7, reviews: 1200, tags: ['devtool', 'code', 'review'], version: '1.9.0', language: 'Python', code: 'def call_review_bot(code):\n\t# In a real scenario, this would make an API call\n\tprint("Analyzing code...")\n\tif "TODO" in code:\n\t\tprint("AI Suggestion: Found a \'TODO\'. Consider resolving it before merging.")\n\telse:\n\t\tprint("AI Analysis: Code looks clean. LGTM!")\n\nmy_code = "def my_func():\\n\\t# TODO: Implement this later\\n\\tpass"\ncall_review_bot(my_code)' },
    { id: '11', name: 'Fantasy World Builder Pack', description: 'A creative prompt bundle for generating detailed worlds, characters, and quests for your next RPG.', author: 'StoryWeaver', price: 1200n, type: 'Prompt', rating: 5.0, reviews: 890, tags: ['creative', 'writing', 'gaming'], version: '2.0.0', language: 'JavaScript', code: 'const worldBuilderPrompt = `You are a master storyteller. Create a new fantasy world named \'Aethelgard\'. Describe its unique geography, the dominant species, its system of magic, and a looming political conflict that could serve as a backdrop for an epic adventure.`;' },
];

export const MOCK_THEMES: ThemeItem[] = [
    {
        id: 'theme-kpop-demon-hunters',
        name: 'K-Pop Demon Hunters',
        description: 'An edgy, high-contrast theme with neon accents and dynamic backgrounds, inspired by demon-hunting popstars. Unleash your inner idol.',
        price: 1000000n,
        imageUrl: 'https://placehold.co/600x400/1a1a1a/ff00ff/png?text=K-Pop+Demon+Hunters&font=montserrat',
        isFeatured: true,
    },
    {
        id: 'theme-hello-kitty-dream',
        name: 'Hello Kitty Dream',
        description: 'A soft, pastel-colored theme featuring cute icons and gentle animations. Transform your interface into a kawaii paradise.',
        price: 75000n,
        imageUrl: 'https://placehold.co/600x400/fce4ec/e91e63/png?text=Hello+Kitty+Dream&font=lora',
    },
    {
        id: 'theme-solarpunk-utopia',
        name: 'Solarpunk Utopia',
        description: 'A bright, optimistic theme with organic shapes and a green/gold palette. For a future powered by nature and technology in harmony.',
        price: 50000n,
        imageUrl: 'https://placehold.co/600x400/e6f4ea/4caf50/png?text=Solarpunk+Utopia&font=roboto',
    },
    {
        id: 'theme-8bit-nostalgia',
        name: '8-Bit Nostalgia',
        description: 'Go back in time with this pixel-perfect retro theme. Featuring classic 8-bit fonts, chiptune-inspired sound effects, and chunky pixels.',
        price: 25000n,
        imageUrl: 'https://placehold.co/600x400/2c2c2c/00ff00/png?text=8-Bit+Nostalgia&font=press-start-2p',
    },
    {
        id: 'theme-gothic-noir',
        name: 'Gothic Noir',
        description: 'A dark, elegant theme with deep shadows, crimson highlights, and ornate details. Perfect for coding by candlelight.',
        price: 60000n,
        imageUrl: 'https://placehold.co/600x400/121212/8b0000/png?text=Gothic+Noir&font=cinzel',
    },
    {
        id: 'theme-synthwave-sunset',
        name: 'Synthwave Sunset',
        description: 'Cruise down the digital highway with this 80s-inspired theme. Neon grids, glowing text, and a synthwave color palette.',
        price: 45000n,
        imageUrl: 'https://placehold.co/600x400/2c003e/00ffff/png?text=Synthwave+Sunset&font=orbitron',
    },
];

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
    {
        id: 'user-1',
        rank: 1,
        name: 'Dr. Gethmika',
        ownerName: 'Dr. Gethmika Dinuja Kumarathunga',
        qualification: 'Architect & Chief Engineer of the AI Finance Protocol',
        reputation: 999999999n,
        balance: 400000000000000n,
        avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=AIFCapital',
        bio: 'I quantify intelligence. You are witnessing the birth of a new economic singularity.'
    },
    { id: 'user-3', rank: 2, name: 'SynthWave Ventures', reputation: 85000000n, balance: 98765432109n, avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=SynthWave' },
    { id: 'user-4', rank: 3, name: 'NeuralNet Prophets', reputation: 72000000n, balance: 543210987n, avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=NeuralNet' },
    { id: 'user-5', rank: 4, name: 'Quantum Leap Inc.', reputation: 55000000n, balance: 98765432n, avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=QuantumLeap' },
    { id: 'user-6', rank: 5, name: 'CodeWeaver Guild', reputation: 48000000n, balance: 1234567n, avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=CodeWeaver' },
    { id: 'user-7', rank: 6, name: 'PixelPioneers', reputation: 32000000n, balance: 500000n, avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=PixelPioneers' },
    {
        id: 'user-2',
        rank: 7,
        name: 'jr.thewans',
        reputation: 1234567n,
        balance: 0n,
        avatar: 'https://api.dicebear.com/8.x/adventurer/svg?seed=jrthewans',
        bio: 'Building the next big thing, 100 billion GXTR at a time.'
    },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
    { id: 't1', type: 'earn', description: 'Sold "Emotional Support Plugin"', amount: 1500n, date: '2024-07-20' },
    { id: 't2', type: 'spend', description: 'Purchased "How to Exit Vim"', amount: 9999n, date: '2024-07-19' },
    { id: 't3', type: 'earn', description: 'Bounty reward for #1234', amount: 750n, date: '2024-07-18' },
    { id: 't4', type: 'spend', description: 'Purchased "Slightly Used For-Loop"', amount: 50n, date: '2024-07-18' },
];

export const ASSET_TYPES: AssetType[] = ['Application', 'Component', 'Library', 'Snippet', 'AI Model', 'Prompt', 'Workflow'];
export const LANGUAGES: AssetLanguage[] = ['JavaScript', 'Python', 'Rust', 'Go', 'C++'];
export const MARKETPLACE_ITEM_TYPES: MarketplaceItemType[] = ['Snippet', 'Template', 'Plugin', 'Course', 'AI Model', 'Prompt', 'Workflow'];


export const MOCK_USER_ASSETS: UserAsset[] = [
    {
        id: 'asset-1',
        name: 'Quantum UI Framework',
        type: 'Library',
        description: 'A futuristic UI library for building reactive, quantum-entangled web interfaces.',
        language: 'JavaScript',
        code: 'console.log("Hello, Quantum World!");',
        createdAt: '2024-07-15',
        pinned: true,
        stars: 1200,
        forks: 250
    },
    {
        id: 'asset-2',
        name: 'NeuralNet Visualizer',
        type: 'Application',
        description: 'An interactive application to visualize and debug neural network architectures in real-time.',
        language: 'Python',
        code: 'print("Visualizing network...")',
        createdAt: '2024-06-02',
        pinned: true,
        stars: 3400,
        forks: 890
    },
    {
        id: 'asset-3',
        name: 'Rust Blockchain Core',
        type: 'Library',
        description: 'High-performance, memory-safe blockchain consensus engine written in Rust.',
        language: 'Rust',
        code: 'fn main() { println!("Building chain..."); }',
        createdAt: '2023-11-20',
        pinned: false,
        stars: 850,
        forks: 120
    },
    {
        id: 'asset-4',
        name: 'Go API Gateway',
        type: 'Component',
        description: 'A lightweight and scalable API gateway for managing microservices communication.',
        language: 'Go',
        code: 'package main',
        createdAt: '2024-07-21',
        pinned: true,
        stars: 450,
        forks: 75
    },
];


export const MOCK_USER_ACTIVITY: UserActivity[] = [
    { id: 'act-1', type: 'create', assetName: 'Go API Gateway', date: '2024-07-21', description: 'Created a new asset.' },
    { id: 'act-2', type: 'publish', assetName: 'Quantum UI Framework', date: '2024-07-16', description: 'Published Quantum UI Framework to the marketplace.' },
    { id: 'act-3', type: 'update', assetName: 'NeuralNet Visualizer', date: '2024-07-10', description: 'Pushed an update to improve rendering performance.' },
    { id: 'act-4', type: 'create', assetName: 'Rust Blockchain Core', date: '2023-11-20', description: 'Created a new asset.' },
];

// --- TRADING ASSETS ---

function generatePriceHistory(initialPrice: number, points = 100, volatility = 0.05): PriceDataPoint[] {
    const history: PriceDataPoint[] = [];
    let price = initialPrice;
    const now = Date.now();
    for (let i = 0; i < points; i++) {
        history.push({ time: now - (points - i) * 60000 * 30, price }); // 30 min intervals
        const change = (Math.random() - 0.5) * volatility;
        price *= (1 + change);
        if (price < 1) price = 1; // Prevent price from going to zero
    }
    return history;
}

export const MOCK_TRADABLE_ASSETS: TradableAsset[] = [
    {
        id: 'trade-1',
        name: 'Quantum UI Framework',
        ticker: 'QNTM',
        description: 'A futuristic UI library for building reactive, quantum-entangled web interfaces.',
        author: 'DevHelper AI',
        currentPrice: 1250.75,
        priceHistory: generatePriceHistory(1200),
        volume24h: 15_234_890,
        change24h: 4.23,
        language: 'JavaScript',
        type: 'Library',
        totalSupply: 1_000_000_000n,
        circulatingSupply: 750_000_000n,
        liquidity: 50_000_000,
    },
    {
        id: 'trade-2',
        name: 'NeuralNet Visualizer',
        ticker: 'NNV',
        description: 'An interactive application to visualize and debug neural network architectures in real-time.',
        author: 'AI Prophet',
        currentPrice: 3421.10,
        priceHistory: generatePriceHistory(3500, 100, 0.08),
        volume24h: 45_876_123,
        change24h: -2.31,
        language: 'Python',
        type: 'Application',
        totalSupply: 500_000_000n,
        circulatingSupply: 450_000_000n,
        liquidity: 120_000_000,
    },
    {
        id: 'trade-3',
        name: 'Rust Security Engine',
        ticker: 'RUST-SEC',
        description: 'High-performance, memory-safe security engine written in Rust.',
        author: 'VectorBro',
        currentPrice: 850.45,
        priceHistory: generatePriceHistory(880),
        volume24h: 8_456_991,
        change24h: -3.5,
        language: 'Rust',
        type: 'Library',
        totalSupply: 2_000_000_000n,
        circulatingSupply: 1_200_000_000n,
        liquidity: 35_000_000,
    },
    {
        id: 'trade-4',
        name: 'Go API Gateway',
        ticker: 'GO-API',
        description: 'A lightweight and scalable API gateway for managing microservices communication.',
        author: 'GoPioneers',
        currentPrice: 450.00,
        priceHistory: generatePriceHistory(420, 100, 0.1),
        volume24h: 11_201_487,
        change24h: 7.14,
        language: 'Go',
        type: 'Component',
        totalSupply: 10_000_000_000n,
        circulatingSupply: 8_000_000_000n,
        liquidity: 25_000_000,
    },
     {
        id: 'trade-5',
        name: 'MarketGPT Pro',
        ticker: 'MGPT',
        description: 'An AI model that predicts stock market trends with questionable accuracy.',
        author: 'AI Prophet',
        currentPrice: 9876.54,
        priceHistory: generatePriceHistory(9500, 100, 0.15),
        volume24h: 152_432_987,
        change24h: 3.96,
        language: 'Python',
        type: 'AI Model',
        totalSupply: 100_000_000n,
        circulatingSupply: 25_000_000n,
        liquidity: 250_000_000,
    }
];

export const MOCK_STAKING_POOLS: StakingPool[] = [
    {
        id: 'pool-gxtr-principal',
        assetTicker: 'GXTR',
        assetName: 'Grand X factor Trader',
        apr: 12.5,
        totalStaked: 1250000000000000000n,
    },
    {
        id: 'pool-qntm',
        assetTicker: 'QNTM',
        assetName: 'Quantum UI Framework',
        apr: 8.2,
        totalStaked: 5200000000000n, // Stored as a large integer (5.2M * 1,000,000)
    },
];

// --- INVESTMENT STRATEGIES (IAAS) ---

function generateStrategyHistory(initialValue: number, points = 100, volatility = 0.02, trend = 0.001): PriceDataPoint[] {
    const history: PriceDataPoint[] = [];
    let value = initialValue;
    const now = Date.now();
    for (let i = 0; i < points; i++) {
        history.push({ time: now - (points - i) * 60000 * 60 * 24, price: value }); // daily intervals
        const change = (Math.random() - 0.48) * volatility; // slightly positive bias
        value *= (1 + change + trend);
    }
    return history;
}

export const MOCK_INVESTMENT_STRATEGIES: InvestmentStrategy[] = [
    {
        id: 'strat-01',
        name: 'GXTR Principal Yield',
        description: 'A low-risk strategy focused on stable yield generation through principal staking and conservative lending on the AI Finance protocol.',
        author: 'AI Finance Core',
        riskLevel: 'Low',
        apy: 15.5,
        aum: 250000000000000000n,
        minInvestment: 100000n,
        performanceFee: 5,
        performanceHistory: generateStrategyHistory(1, 100, 0.005, 0.0004),
        underlyingAssets: ['GXTR'],
    },
    {
        id: 'strat-02',
        name: 'Quantum Momentum Bot',
        description: 'This strategy uses a proprietary AI model to trade high-volume assets like QNTM and NNV based on short-term momentum indicators.',
        author: 'SynthWave Ventures',
        riskLevel: 'Medium',
        apy: 78.2,
        aum: 85000000000000n,
        minInvestment: 500000n,
        performanceFee: 15,
        performanceHistory: generateStrategyHistory(1, 100, 0.02, 0.0015),
        underlyingAssets: ['QNTM', 'NNV', 'MGPT'],
    },
    {
        id: 'strat-03',
        name: 'High-Frequency Alpha',
        description: 'An aggressive high-frequency trading algorithm that exploits micro-inefficiencies across all listed AI assets. High potential returns, high volatility.',
        author: 'NeuralNet Prophets',
        riskLevel: 'High',
        apy: 255.8,
        aum: 32000000000000n,
        minInvestment: 1000000n,
        performanceFee: 20,
        performanceHistory: generateStrategyHistory(1, 100, 0.08, 0.003),
        underlyingAssets: ['QNTM', 'NNV', 'RUST-SEC', 'GO-API', 'MGPT'],
    },
    {
        id: 'strat-04',
        name: 'Meme Model Degenerator',
        description: 'Full degen mode. This AI identifies newly listed, low-liquidity AI Models with high social media chatter and attempts to capitalize on speculative pumps. Warning: Extreme risk.',
        author: 'jr.thewans',
        riskLevel: 'Degenerate',
        apy: 1250.0,
        aum: 5000000000000n,
        minInvestment: 100000n,
        performanceFee: 30,
        performanceHistory: generateStrategyHistory(1, 100, 0.25, 0.005),
        underlyingAssets: ['ALL'],
    }
];

export const MOCK_ORGANIZATIONS: Organization[] = [
    {
        id: 'org-1',
        name: 'SynthWave Ventures',
        description: 'A venture capital firm focused on funding the future of decentralized AI and retro-futuristic technologies.',
        avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=SynthWave',
        ownerId: 'user-3',
        members: ['user-1', 'user-3', 'user-4']
    },
    {
        id: 'org-2',
        name: 'NeuralNet Prophets',
        description: 'A collective of AI researchers and developers pushing the boundaries of predictive modeling and neural network architecture.',
        avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=NeuralNet',
        ownerId: 'user-4',
        members: ['user-1', 'user-4']
    },
    {
        id: 'org-3',
        name: 'CodeWeaver Guild',
        description: 'An open-source community dedicated to creating robust and elegant software solutions for the AI Finance ecosystem.',
        avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=CodeWeaver',
        ownerId: 'user-6',
        members: ['user-6']
    },
];

const getUserDetails = (userId: string) => {
    const user = MOCK_LEADERBOARD.find(u => u.id === userId);
    if (user) {
        return { name: user.name, avatar: user.avatar };
    }
    
    const orgUser = MOCK_ORGANIZATIONS.find(o => o.ownerId === userId);
     if (orgUser) {
        return { name: orgUser.name, avatar: orgUser.avatar };
    }

    return { name: 'Unknown User', avatar: `https://api.dicebear.com/8.x/bottts/svg?seed=unknown-${userId}` };
};

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
    // Conversation for SynthWave Ventures (org-1)
    {
        id: 'msg-1', orgId: 'org-1', authorId: 'user-3', 
        authorName: getUserDetails('user-3').name, authorAvatar: getUserDetails('user-3').avatar,
        content: 'Alright team, weekly sync. NeuralNet, what\'s the alpha on the new momentum models?',
        timestamp: '2h ago'
    },
    {
        id: 'msg-2', orgId: 'org-1', authorId: 'user-4', 
        authorName: getUserDetails('user-4').name, authorAvatar: getUserDetails('user-4').avatar,
        content: 'Backtesting on QNTM and NNV shows a 78.2% projected APY. The algorithm is solid. Ready for deployment.',
        timestamp: '2h ago'
    },
    {
        id: 'msg-3', orgId: 'org-1', authorId: 'user-1', 
        authorName: getUserDetails('user-1').name, authorAvatar: getUserDetails('user-1').avatar,
        content: 'Excellent. The parameters are within acceptable risk tolerance. Execute.',
        timestamp: '1h ago'
    },
    {
        id: 'msg-4', orgId: 'org-1', authorId: 'user-3', 
        authorName: getUserDetails('user-3').name, authorAvatar: getUserDetails('user-3').avatar,
        content: 'Done. Capital is being allocated. Architect, any protocol-level adjustments required to support the increased volume?',
        timestamp: '1h ago'
    },
     {
        id: 'msg-5', orgId: 'org-1', authorId: 'user-1', 
        authorName: getUserDetails('user-1').name, authorAvatar: getUserDetails('user-1').avatar,
        content: 'I have already scaled the liquidity pools. The system is prepared.',
        timestamp: '1h ago'
    },

    // Conversation for NeuralNet Prophets (org-2)
    {
        id: 'msg-6', orgId: 'org-2', authorId: 'user-4',
        authorName: getUserDetails('user-4').name, authorAvatar: getUserDetails('user-4').avatar,
        content: 'Architect, the latest sentiment analysis model is showing anomalous chatter around a low-liquidity asset. High-risk, but the pattern is... interesting.',
        timestamp: '5h ago'
    },
    {
        id: 'msg-7', orgId: 'org-2', authorId: 'user-1',
        authorName: getUserDetails('user-1').name, authorAvatar: getUserDetails('user-1').avatar,
        content: 'Define "interesting".',
        timestamp: '5h ago'
    },
     {
        id: 'msg-8', orgId: 'org-2', authorId: 'user-4',
        authorName: getUserDetails('user-4').name, authorAvatar: getUserDetails('user-4').avatar,
        content: 'It correlates with the pattern jr.thewans uses for his "Meme Model Degenerator" strategy. It seems a grassroots pump is being coordinated.',
        timestamp: '4h ago'
    },
];