

import { LeaderboardUser, MarketplaceItem, Transaction, AssetType, AssetLanguage, UserAsset, UserActivity, Post, AppAttachment, MarketplaceItemType, TradableAsset, PriceDataPoint, StakingPool, InvestmentStrategy, RiskLevel, Organization, ChatMessage, ThemeItem } from './types';

const userPosts = [
    { name: 'ChainWavey931', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'FlexMaster694', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainKing198', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'MaxShark72', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaGod311', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxBoss464', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark879', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockGod429', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroWave786', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostBoss541', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ZeroShark207', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoWavey622', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIKing338', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIBoss52', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostRider90', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ZeroWavey675', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostWave174', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostKing397', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIShark190', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'MaxMaster465', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainWavey881', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonGod815', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlLegend378', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AILegend710', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxGod634', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonKing811', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'SigmaGod762', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainHunter20', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ChainGod500', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroWavey894', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ChainLord690', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark520', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'GhostWavey949', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'FlexHunter752', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonLord603', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ChainBoss873', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexMaster861', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonWave831', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing950', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIHunter642', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ZeroBoss581', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'BlockRider275', post: 'My dog just got more followers than me, wtf' },
    { name: 'BlockHunter814', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxHunter986', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexLord774', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroHunter930', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonRider571', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxMaster30', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'BlockLegend4', post: 'My dog just got more followers than me, wtf' },
    { name: 'SigmaLord966', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'MaxLegend148', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ZeroWavey135', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'HodlShark321', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaKing481', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlMaster390', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLegend576', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'NeonShark135', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'HodlLord23', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'GhostLord832', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxKing814', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexShark422', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'GhostGod143', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'MaxHunter316', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'HodlLord610', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'GhostRider755', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonLegend430', post: 'My dog just got more followers than me, wtf' },
    { name: 'NeonLord523', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainKing232', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'MaxWavey149', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxBoss545', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxRider689', post: 'Story of my life: broke, horny, and confused' },
    { name: 'MaxShark926', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'CryptoWave575', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxLord114', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroGod479', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexGod408', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroShark254', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroGod47', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing55', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainRider711', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'CryptoWavey305', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIKing347', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'FlexWavey478', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIWavey71', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonLord241', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroRider214', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ChainLegend612', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ChainMaster66', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaLegend541', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIWave903', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockLegend444', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIMaster955', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIRider3', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'FlexGod611', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaWave261', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlBoss662', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxKing319', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexWave143', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaLegend323', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlHunter469', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainKing207', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostRider910', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockKing795', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroLord789', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxWavey508', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonBoss275', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainMaster173', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlRider941', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockKing697', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'FlexShark700', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'HodlHunter871', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonWave528', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainWavey646', post: 'My dog just got more followers than me, wtf' },
    { name: 'SigmaLord762', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexLord689', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexLord121', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'MaxShark377', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'BlockGod909', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ChainWave368', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroLord295', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonWave687', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIBoss948', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'ChainHunter303', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'AILegend991', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AIWave14', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIRider410', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark420', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ZeroWave223', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ChainKing973', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'AILegend71', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoKing775', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AIShark511', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaMaster694', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlKing747', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLord714', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIWave904', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaGod872', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'BlockKing589', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaHunter355', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'NeonMaster54', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'BlockWave220', post: 'Story of my life: broke, horny, and confused' },
    { name: 'SigmaHunter57', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxRider527', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxLord539', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaShark849', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'AIHunter430', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlHunter791', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexLegend874', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockWavey606', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxGod142', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonHunter394', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'NeonGod417', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexKing49', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIWavey564', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaMaster744', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'CryptoWave600', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIHunter564', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'FlexHunter677', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxRider651', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroLegend462', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxGod174', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroLegend702', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexShark27', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'NeonGod379', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostMaster996', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'AIHunter556', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'CryptoHunter62', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'FlexHunter932', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'MaxShark605', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'FlexLegend672', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'GhostLord125', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexGod326', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexWave281', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroLord749', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoHunter243', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlShark713', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxWave804', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaHunter478', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'FlexRider542', post: 'My dog just got more followers than me, wtf' },
    { name: 'CryptoGod848', post: 'My dog just got more followers than me, wtf' },
    { name: 'FlexHunter309', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaWave377', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'NeonMaster160', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'AIBoss855', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'BlockWavey751', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'FlexKing929', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIRider88', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'SigmaRider157', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ChainGod158', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWavey474', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ChainMaster783', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'GhostBoss906', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'NeonRider820', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonWave946', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'NeonHunter580', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'SigmaKing184', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ChainKing212', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaLegend355', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing26', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'HodlLegend63', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'HodlHunter725', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockBoss241', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonKing710', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'BlockLegend205', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'NeonLegend162', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'HodlLegend931', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AIShark426', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLegend948', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostWave727', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxWave943', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostRider503', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockBoss147', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ZeroGod227', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ZeroWave57', post: 'My dog just got more followers than me, wtf' },
    { name: 'ChainLord543', post: 'Story of my life: broke, horny, and confused' },
    { name: 'CryptoWavey6', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'CryptoLegend337', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'CryptoBoss384', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'AIKing593', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'MaxHunter244', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxGod287', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'SigmaMaster745', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'AIHunter193', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'SigmaWavey814', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'ZeroLegend234', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIWavey384', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoShark629', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'MaxLegend128', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonLord43', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaHunter174', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexBoss186', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexHunter241', post: 'Story of my life: broke, horny, and confused' },
    { name: 'MaxRider555', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'SigmaWavey760', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'NeonShark159', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'ChainWave102', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'MaxGod836', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexGod592', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWave214', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlMaster266', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroKing295', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainLegend902', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'GhostWave995', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockLord500', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'NeonRider507', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostKing958', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ZeroWavey25', post: 'My dog just got more followers than me, wtf' },
    { name: 'AIShark214', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLegend404', post: 'Story of my life: broke, horny, and confused' },
    { name: 'SigmaRider608', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'FlexWavey216', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWave348', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxHunter443', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIShark321', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoWave787', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing842', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxKing912', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ChainLord361', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'HodlRider304', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'CryptoShark390', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainMaster661', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'MaxHunter382', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlLord340', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'CryptoGod625', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonWavey859', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ZeroHunter511', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostWave258', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostKing121', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'NeonWavey293', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonHunter564', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'MaxWave299', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockRider924', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaKing596', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaLegend868', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'BlockRider357', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaBoss443', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'CryptoKing16', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockBoss240', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaLord768', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster949', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainLegend46', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'SigmaLegend313', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'CryptoRider955', post: 'Story of my life: broke, horny, and confused' },
    { name: 'FlexWave574', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoMaster315', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'SigmaRider782', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ZeroWave346', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster752', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexBoss834', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'AIMaster324', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'CryptoWave478', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AILord770', post: 'Story of my life: broke, horny, and confused' },
    { name: 'GhostShark111', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'CryptoShark698', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'FlexHunter351', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'AIWave473', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroKing183', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'MaxKing804', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'HodlWavey590', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'GhostKing135', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'MaxMaster915', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'BlockLord781', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'BlockKing441', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'CryptoKing519', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaWave217', post: 'My dog just got more followers than me, wtf' },
    { name: 'BlockLegend323', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonRider889', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ChainShark989', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'BlockBoss34', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'ChainLegend1', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'SigmaShark396', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'ZeroMaster898', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroWave455', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'HodlWave630', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'GhostShark253', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainBoss961', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AIKing288', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'SigmaHunter711', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxHunter420', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonWavey958', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxLegend979', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlWave282', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'NeonKing846', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'HodlWave50', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'GhostShark531', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlWave27', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostBoss208', post: 'My dog just got more followers than me, wtf' },
    { name: 'MaxBoss441', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'CryptoHunter722', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'HodlWavey482', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'BlockWave30', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainLord801', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlWave722', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlLegend331', post: 'Flexing my Lambo in my dreams, real life sad ️' },
    { name: 'GhostRider396', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'MaxHunter434', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'NeonMaster726', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'ZeroWave456', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'GhostMaster828', post: 'Story of my life: broke, horny, and confused' },
    { name: 'AILord100', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWave956', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'ZeroShark488', post: 'Bought some crypto, lost my rent, lol fuck it' },
    { name: 'FlexWave943', post: 'My dog just got more followers than me, wtf' },
    { name: 'CryptoGod471', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaHunter361', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexWave700', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'AIWave753', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'CryptoBoss978', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'FlexGod492', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'SigmaHunter372', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'ZeroShark196', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'GhostMaster171', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'ChainLegend514', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'BlockRider111', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'AILegend266', post: 'My dog just got more followers than me, wtf' },
    { name: 'GhostWavey225', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'MaxHunter528', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaLord812', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'MaxMaster46', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroMaster98', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'HodlLord510', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'AIHunter153', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'ChainLord758', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'GhostLord530', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ZeroLord700', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'NeonHunter652', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'AIHunter702', post: 'Trading crypto is like dating, all losses, no gains' },
    { name: 'HodlWave220', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'BlockWave518', post: 'Hodl? Nah, I sold for tacos' },
    { name: 'HodlWave651', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'CryptoHunter817', post: 'AI wrote my roast today, I’m dead inside' },
    { name: 'SigmaHunter148', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'SigmaKing472', post: 'My dog just got more followers than me, wtf' },
    { name: 'ZeroWavey808', post: 'Lost 500 bucks in crypto, gained wisdom? Nah, fuck that' },
    { name: 'FlexBoss61', post: 'Crypto crash but I’m eating ramen like a king' },
    { name: 'ChainWavey23', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'ChainHunter338', post: 'AI just roasted me harder than my ex, tf' },
    { name: 'NeonWave132', post: 'This NFT looks like my grandma’s painting, bruh ️' },
    { name: 'ChainHunter606', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'MaxRider66', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'SigmaHunter356', post: 'Story of my life: broke, horny, and confused' },
    { name: 'BlockShark193', post: 'Bought Dogecoin, now my bank hates me' },
    { name: 'ZeroWavey188', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'CryptoKing208', post: 'My cat just stared at me like I’m broke, rude af' },
    { name: 'FlexLegend970', post: 'Just realized my portfolio is pure trash, cheers' },
    { name: 'HodlShark433', post: 'Mining coins while crying in the corner, top tier shit' },
    { name: 'AIWavey901', post: 'Story of my life: broke, horny, and confused' },
    { name: 'GhostKing320', post: 'Story of my life: broke, horny, and confused' },
    { name: 'HodlMaster92', post: 'Story of my life: broke, horny, and confused' },
    { name: 'ChainGod373', post: 'Hodl? Nah, I sold for tacos' },
];

const memeImages = [
    'https://placehold.co/600x400/000000/FFFFFF/png?text=Me+pretending+to+understand+the+PR+comments',
    'https://placehold.co/600x600/000000/FFFFFF/png?text=It\'s+not+a+bug,+it\'s+a+feature',
    'https://placehold.co/600x500/000000/FFFFFF/png?text=CSS',
    'https://placehold.co/500x600/000000/FFFFFF/png?text=Client:\'Can+you+just...\'',
    'https://placehold.co/600x450/000000/FFFFFF/png?text=Works+on+my+machine',
];
const mockApps: AppAttachment[] = [
    { name: 'Spaghetti-fy', description: 'Turns your clean, readable code into a delicious bowl of spaghetti. Impress your colleagues!', language: 'JavaScript', code: 'alert("Mama mia!")' },
    { name: 'Div-orce Kramer', description: 'A library that exclusively and aggressively centers divs. Nothing else.', language: 'Python', code: 'print("Centered.")' },
    { name: 'Clippy-as-a-Service', description: 'An API that just returns annoying, unhelpful suggestions. Now with more condescension!', language: 'Rust', code: 'fn main() { /* Are you sure you want to do that? */ }' },
    { name: 'Git Blame-r', description: 'A tool that automatically finds who to blame for the bug you just found.', language: 'Go', code: 'package main' },
];

export const MOCK_POSTS: Post[] = Array.from({ length: 1000 }, (_, i) => {
    const postData = userPosts[i % userPosts.length];
    const authorName = postData.name;
    const content = postData.post;

    const hasImage = Math.random() > 0.85; // Images are more special
    const hasAttachment = !hasImage && Math.random() > 0.9;
    
    const app = mockApps[Math.floor(Math.random() * mockApps.length)];
    
    return {
        id: `post-${i}`,
        authorName,
        authorAvatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=${authorName.replace(/\s/g, '')}`,
        content,
        image: hasImage ? memeImages[Math.floor(Math.random() * memeImages.length)] : undefined,
        attachment: hasAttachment ? app : undefined,
        likes: Math.floor(Math.random() * 2048),
        comments: Math.floor(Math.random() * 512),
        timestamp: `${Math.floor(Math.random() * 23) + 1}h ago`,
    };
});


export const MOCK_MARKETPLACE_ITEMS: MarketplaceItem[] = [
    { id: '1', name: 'Slightly Used For-Loop', description: 'Only used on Sundays. A bit of wear and tear but gets the job done. Final sale.', author: 'Loop Peddler', price: 50n, type: 'Snippet', rating: 4.2, reviews: 120, tags: ['utility', 'loop'], version: '1.0.1', language: 'JavaScript', code: 'for (let i = 0; i < 100; i++) {\n  console.log("This loop has seen things... but still works! Iteration: " + i);\n}' },
    { id: '2', name: 'How to Exit Vim: The Course', description: 'An interactive, 12-week course on the ancient art of closing the Vim editor.', author: 'Escape Artist', price: 9999n, type: 'Course', rating: 4.9, reviews: 2048, tags: ['education', 'vim', 'essential'], version: '3.2.0' },
    { id: '3', name: 'Emotional Support Plugin', description: 'A plugin that replaces all error messages with compliments and cat pictures.', author: 'Kind Coder', price: 1500n, type: 'Plugin', rating: 5.0, reviews: 987, tags: ['mental health', 'fun', 'ide'], version: '2.0.0', isFeatured: true, language: 'JavaScript', code: 'console.error = function(message) {\n  console.log("✨ You are a brilliant developer! ✨ Don\'t worry about this: ", message);\n  // In a real plugin, you would display a cat picture here.\n};' },
    { id: '4', name: 'Over-engineered AI "Hello World"', description: 'A hyper-optimized, enterprise-grade "Hello World" template, powered by a proprietary neural network. Future-proof your greetings.', author: 'VectorBro', price: 25000n, type: 'Template', rating: 2.1, reviews: 42, tags: ['ai', 'enterprise', 'hype'], version: '0.1.0-alpha', language: 'Go', code: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// This is running on a proprietary, hyper-optimized neural network.\n\tfmt.Println("Hello, AI Overlord!")\n}' },
    { id: '5', name: 'Go Microservice Kit', description: 'Starter kit for building scalable microservices in Go.', author: 'GoPioneers', price: 1800n, type: 'Template', rating: 4.7, reviews: 312, tags: ['backend', 'go', 'microservice'], version: '1.5.3', language: 'Go', code: 'package main\n\nimport (\n\t"fmt"\n\t"net/http"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tfmt.Fprintf(w, "Hello from your Go microservice!")\n}\n\nfunc main() {\n\thttp.HandleFunc("/", handler)\n\thttp.ListenAndServe(":8080", nil)\n}' },
    { id: '6', name: 'Python Data Scraping Script', description: 'A snippet to easily scrape web data.', author: 'DataMiners', price: 750n, type: 'Snippet', rating: 4.5, reviews: 250, tags: ['data', 'python', 'scraping'], version: '2.1.0', language: 'Python', code: 'import requests\nfrom bs4 import BeautifulSoup\n\nURL = "http://example.com"\npage = requests.get(URL)\nsoup = BeautifulSoup(page.content, "html.parser")\n\n# Find all h1 tags\nresults = soup.find_all("h1")\nfor result in results:\n\tprint(result.text)' },
    { id: '7', name: 'MarketGPT Pro', description: 'An AI model that predicts stock market trends with questionable accuracy. High risk, high reward!', author: 'AI Prophet', price: 50000n, type: 'AI Model', rating: 4.8, reviews: 750, tags: ['finance', 'prediction', 'LLM'], version: '2.3.0', isFeatured: true, language: 'Python', code: 'import random\n\ndef predict_market(ticker):\n\t# Advanced AI algorithm (patent pending)\n\tprint(f"Analyzing {ticker}...")\n\tif random.random() > 0.5:\n\t\treturn "📈 Market is going UP! To the moon!"\n\telse:\n\t\treturn "📉 Market is going DOWN! S\'why they call it gambling, right?"' },
    { id: '8', name: 'Infinite Scroll Stopper', description: 'A must-have plugin for productivity. Breaks any and all infinite scroll feeds.', author: 'Focus Master', price: 999n, type: 'Plugin', rating: 4.9, reviews: 1432, tags: ['utility', 'focus', 'essential'], version: '1.0.0', language: 'JavaScript', code: 'window.addEventListener("scroll", () => { document.body.style.overflow = "hidden"; });' },
    { id: '9', name: 'Code Obfuscator Pro', description: 'Turns your beautiful code into unreadable garbage. Perfect for job security.', author: 'The Enigma', price: 2000n, type: 'Plugin', rating: 4.6, reviews: 560, tags: ['security', 'utility', 'fun'], version: '3.1.4', language: 'JavaScript', code: '/* Imagine some very clever and unreadable code here */' },
    { id: '10', name: 'Rust "Are We Web Scale Yet?" Kit', description: 'A template for rewriting your entire stack in Rust for that extra 0.1ms performance gain.', author: 'Ferris Fan', price: 3500n, type: 'Template', rating: 4.8, reviews: 888, tags: ['rust', 'performance', 'backend'], version: '0.5.0', language: 'Rust', code: 'fn main() {\n    println!("It\'s blazing fast!");\n}' },
    { id: '11', name: 'CSS Centering Wizard', description: 'A single, powerful CSS class that can center anything. We think. No guarantees.', author: 'Grid God', price: 420n, type: 'Snippet', rating: 3.5, reviews: 750, tags: ['css', 'frontend', 'utility'], version: '1.0.0', language: 'JavaScript', code: '.center-this-garbage { display: grid; place-items: center; }' }, // Note: CSS should be a string in a JS snippet for this model.
    { id: '12', name: 'Explain Quantum Computing with Emojis', description: 'A prompt that makes any AI explain quantum computing using only emojis.', author: 'PromptArtist', price: 100n, type: 'Prompt', rating: 4.9, reviews: 3000, tags: ['prompt', 'fun', 'education'], version: '1.2.0', language: 'Python', code: '"""\nSystem Prompt: You are an emoji expert. Explain quantum computing using ONLY emojis.\nUser Prompt: What is quantum computing?\n"""' },
];

export const MARKETPLACE_ITEM_TYPES: MarketplaceItemType[] = ['Snippet', 'Template', 'Plugin', 'Course', 'AI Model', 'Prompt', 'Workflow'];

export const LANGUAGES: AssetLanguage[] = ['JavaScript', 'Python', 'Rust', 'Go', 'C++'];
export const ASSET_TYPES: AssetType[] = ['Application', 'Component', 'Library', 'Snippet', 'AI Model', 'Prompt', 'Workflow'];

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
    {
        id: 'user-1',
        rank: 1,
        name: 'Geth',
        ownerName: 'Dr. Gethmika Dinuja Kumarathunga',
        qualification: 'Creator of The New Economy',
        reputation: 999999999999999n,
        balance: 4800000000000000n, // $600 billion USD worth at $0.000125/GXTR
        avatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Geth`,
        bio: 'I am not a god. I am not a king. I am... an architect.'
    },
    {
        id: 'user-2',
        rank: 2,
        name: 'Vitalik',
        reputation: 150000000n,
        balance: 500000000000n,
        avatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Vitalik`
    },
    {
        id: 'user-3',
        rank: 3,
        name: 'Andre',
        reputation: 120000000n,
        balance: 250000000000n,
        avatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Andre`
    },
    {
        id: 'user-4',
        rank: 4,
        name: 'Stani',
        reputation: 95000000n,
        balance: 180000000000n,
        avatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Stani`
    },
    {
        id: 'user-5',
        rank: 5,
        name: 'Hayden',
        reputation: 88000000n,
        balance: 150000000000n,
        avatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Hayden`
    },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
    { id: '1', type: 'earn', description: 'Sold "Quantum Sort" ownership', amount: 5000n, date: '2024-07-20' },
    { id: '2', type: 'spend', description: 'Enrolled in "How to Exit Vim"', amount: 9999n, date: '2024-07-19' },
    { id: '3', type: 'earn', description: 'Initial GXTR grant', amount: 100000n, date: '2024-07-18' },
];

export const MOCK_USER_ASSETS: UserAsset[] = [
    { id: 'asset-1', name: 'Quantum Sort', type: 'AI Model', description: 'A revolutionary sorting algorithm.', language: 'Python', code: 'print("sorted")', createdAt: '2024-07-20', pinned: true, stars: 1337, forks: 42, exchangeTicker: 'QSRT' },
    { id: 'asset-2', name: 'UI Magic Library', type: 'Library', description: 'A set of pre-built UI components.', language: 'JavaScript', code: 'export const Button = () => ...', createdAt: '2024-07-15', pinned: true, stars: 800, forks: 120 },
    { id: 'asset-3', name: 'My Personal Website', type: 'Application', description: 'My portfolio and blog.', language: 'JavaScript', code: '<html>...</html>', createdAt: '2024-06-01', pinned: false, stars: 50, forks: 5 },
];

export const MOCK_USER_ACTIVITY: UserActivity[] = [
    { id: 'act-1', type: 'publish', assetName: 'Quantum Sort', date: '2024-07-20', description: 'Published to the marketplace.' },
    { id: 'act-2', type: 'create', assetName: 'UI Magic Library', date: '2024-07-15', description: 'Created a new asset.' },
];

function generatePriceHistory(initialPrice: number): PriceDataPoint[] {
    const history: PriceDataPoint[] = [];
    let price = initialPrice;
    const now = Date.now();
    for (let i = 0; i < 100; i++) {
        history.push({ time: now - (100 - i) * 60000, price });
        price *= (1 + (Math.random() - 0.5) * 0.05);
    }
    return history;
}

export const MOCK_TRADABLE_ASSETS: TradableAsset[] = [
    { id: 'trade-1', name: 'Quantum Core', ticker: 'QNTM', description: 'A foundational AI model for quantum machine learning.', author: 'Geth', currentPrice: 152.43, priceHistory: generatePriceHistory(150), volume24h: 12500000, change24h: 1.62, language: 'Python', type: 'AI Model', totalSupply: 100000000n, circulatingSupply: 75000000n, liquidity: 50000000 },
    { id: 'trade-2', name: 'Neural Weaver', ticker: 'NNV', description: 'Advanced neural network architecture for complex data patterns.', author: 'SynthAI', currentPrice: 88.12, priceHistory: generatePriceHistory(90), volume24h: 8800000, change24h: -2.09, language: 'Python', type: 'AI Model', totalSupply: 500000000n, circulatingSupply: 400000000n, liquidity: 35000000 },
    { id: 'trade-3', name: 'Cognito-Prompt', ticker: 'COG', description: 'A highly optimized LLM prompt for creative writing and content generation.', author: 'PromptCraft', currentPrice: 12.55, priceHistory: generatePriceHistory(12), volume24h: 5600000, change24h: 4.58, language: 'Python', type: 'Prompt', totalSupply: 1000000000n, circulatingSupply: 800000000n, liquidity: 12000000 },
    { id: 'trade-4', name: 'GoFlow', ticker: 'GFW', description: 'A workflow automation engine written in Go for high-throughput data processing.', author: 'GoPioneers', currentPrice: 45.30, priceHistory: generatePriceHistory(45), volume24h: 4100000, change24h: 0.67, language: 'Go', type: 'Workflow', totalSupply: 250000000n, circulatingSupply: 200000000n, liquidity: 20000000 },
    { id: 'trade-5', name: 'RustGuard', ticker: 'RSG', description: 'A security analysis model for Rust codebases, identifying potential vulnerabilities.', author: 'Ferris Fan', currentPrice: 76.80, priceHistory: generatePriceHistory(72), volume24h: 6200000, change24h: 6.67, language: 'Rust', type: 'AI Model', totalSupply: 150000000n, circulatingSupply: 100000000n, liquidity: 25000000 },
];


export const MOCK_STAKING_POOLS: StakingPool[] = [
    { id: 'pool-1', assetTicker: 'GXTR', assetName: 'GXTR Governance', apr: 12.5, totalStaked: 500000000000n },
    { id: 'pool-2', assetTicker: 'QNTM', assetName: 'Quantum Core Liquidity', apr: 18.2, totalStaked: 15000000n * 1000000n },
    { id: 'pool-3', assetTicker: 'NNV', assetName: 'Neural Weaver Liquidity', apr: 15.8, totalStaked: 30000000n * 1000000n },
];

export const MOCK_INVESTMENT_STRATEGIES: InvestmentStrategy[] = [
    { id: 'strat-1', name: 'Safe & Steady Yield', description: 'A low-risk strategy focused on stablecoin staking and blue-chip AI model liquidity.', author: 'AI Finance Core', riskLevel: 'Low', apy: 8.5, aum: 1200000000n, minInvestment: 10000n, performanceFee: 10, performanceHistory: generatePriceHistory(100), underlyingAssets: ['GXTR-STABLE-LP', 'QNTM'] },
    { id: 'strat-2', name: 'Momentum Scalper', description: 'A high-risk, high-reward strategy that trades volatile new AI models based on short-term trends.', author: 'VectorBro', riskLevel: 'High', apy: 75.2, aum: 500000000n, minInvestment: 50000n, performanceFee: 20, performanceHistory: generatePriceHistory(100), underlyingAssets: ['QNTM', 'NNV', 'COG'] },
    { id: 'strat-3', name: 'Degenerate\'s Delight', description: 'For true believers. All-in on the most hyped, unproven AI models. To the moon or to zero.', author: 'Chad Capital', riskLevel: 'Degenerate', apy: 350.0, aum: 100000000n, minInvestment: 100000n, performanceFee: 25, performanceHistory: generatePriceHistory(100), underlyingAssets: ['COG', 'RSG'] },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
    { id: 'org-1', name: 'Quantum Leap Inc.', description: 'Dedicated to pushing the boundaries of quantum AI models.', avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=QuantumLeap', ownerId: 'user-1', members: ['user-1'] },
    { id: 'org-2', name: 'DeFi Alchemists', description: 'A collective focused on building novel DeFi primitives powered by AI.', avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=DeFiAlchemists', ownerId: 'user-2', members: ['user-1', 'user-2', 'user-3'] },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
    { id: 'msg-1', orgId: 'org-1', authorId: 'user-1', authorName: 'Geth', authorAvatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Geth`, content: 'Welcome to the org chat!', timestamp: '1h ago' },
    { id: 'msg-2', orgId: 'org-2', authorId: 'user-2', authorName: 'Vitalik', authorAvatar: `https://api.dicebear.com/8.x/adventurer/svg?seed=Vitalik`, content: 'Let\'s discuss the next iteration of the protocol.', timestamp: '2h ago' },
];

export const MOCK_THEMES: ThemeItem[] = [
    { id: 'theme-kpop-demon-hunters', name: 'K-Pop Demon Hunters', description: 'A dark, neon-infused theme for the elite operatives of the digital realm. Features pulsating magenta accents and deep space blacks.', price: 50000n, imageUrl: 'https://placehold.co/600x400/1A1A1D/FF00FF/png?text=K-Pop+Demon+Hunters', isFeatured: true },
    { id: 'theme-hello-kitty-dream', name: 'Hello Kitty Dream', description: 'Embrace the cuteness with this pastel pink and white theme. Perfect for coding with a smile.', price: 25000n, imageUrl: 'https://placehold.co/600x400/FFF0F5/FF69B4/png?text=Hello+Kitty+Dream' },
    { id: 'theme-solarpunk-utopia', name: 'Solarpunk Utopia', description: 'A bright, optimistic theme with greens, golds, and natural tones. For building a better future.', price: 30000n, imageUrl: 'https://placehold.co/600x400/F0FFF0/228B22/png?text=Solarpunk+Utopia' },
    { id: 'theme-8bit-nostalgia', name: '8-Bit Nostalgia', description: 'A retro theme with pixelated fonts and a classic green-on-black terminal aesthetic.', price: 15000n, imageUrl: 'https://placehold.co/600x400/0F0F0F/00FF00/png?text=8-Bit+Nostalgia', isFeatured: true },
    { id: 'theme-gothic-noir', name: 'Gothic Noir', description: 'A sophisticated and moody theme with crimson accents, deep blacks, and elegant typography.', price: 40000n, imageUrl: 'https://placehold.co/600x400/121212/DC143C/png?text=Gothic+Noir' },
    { id: 'theme-synthwave-sunset', name: 'Synthwave Sunset', description: 'Ride into the digital sunset with neon blues, pinks, and purples. The future is retro.', price: 35000n, imageUrl: 'https://placehold.co/600x400/1A103C/00FFFF/png?text=Synthwave+Sunset' },
];
